Repository deckhouse/csi-nfs, pull requests merged in 2024-09, with the labels that each got.

#34 [CI] Add images check with Trivy
  .github/workflows/trivy_check.yaml
  .github/workflows/trivy_image_check.yaml
  .golangci.yaml
  .werf/images-digests.yaml
  images/controller/werf.inc.yaml
  images/csi-nfs/werf.inc.yaml
  images/webhooks/werf.inc.yaml
  trivy-silent.yaml
Labels: enhancement

#35 [docs] Small fixes in Quickstart Guide
  docs/README.md
  docs/README_RU.md
Labels: documentation

#37 [controller] Fix CSI NFS v3(tcp) support
  .werf/bundle.yaml
  charts/deckhouse_lib_helm-1.22.0.tgz
  charts/helm_lib/Chart.yaml
  charts/helm_lib/LICENSE
  charts/helm_lib/README.md
  charts/helm_lib/templates/_api_version_and_kind.tpl
  charts/helm_lib/templates/_csi_controller.tpl
  charts/helm_lib/templates/_csi_node.tpl
  charts/helm_lib/templates/_enable_ds_eviction.tpl
  charts/helm_lib/templates/_envs_for_proxy.tpl
  charts/helm_lib/templates/_high_availability.tpl
  charts/helm_lib/templates/_kube_rbac_proxy.tpl
  charts/helm_lib/templates/_module_documentation_uri.tpl
  charts/helm_lib/templates/_module_ephemeral_storage.tpl
  charts/helm_lib/templates/_module_generate_common_name.tpl
  charts/helm_lib/templates/_module_https.tpl
  charts/helm_lib/templates/_module_image.tpl
  charts/helm_lib/templates/_module_ingress_class.tpl
  charts/helm_lib/templates/_module_init_container.tpl
  charts/helm_lib/templates/_module_labels.tpl
  charts/helm_lib/templates/_module_name.tpl
  charts/helm_lib/templates/_module_public_domain.tpl
  charts/helm_lib/templates/_module_security_context.tpl
  charts/helm_lib/templates/_module_storage_class.tpl
  charts/helm_lib/templates/_monitoring_grafana_dashboards.tpl
  charts/helm_lib/templates/_monitoring_prometheus_rules.tpl
  charts/helm_lib/templates/_node_affinity.tpl
  charts/helm_lib/templates/_pod_disruption_budget.tpl
  charts/helm_lib/templates/_priority_class.tpl
  charts/helm_lib/templates/_resources_management.tpl
  charts/helm_lib/templates/_spec_for_high_availability.tpl
  images/csi-nfs/werf.inc.yaml
  images/wait-rpcbind/src/cmd/main.go
  images/wait-rpcbind/src/go.mod
  images/wait-rpcbind/src/go.sum
  images/wait-rpcbind/werf.inc.yaml
  templates/csi/controller.yaml
Labels: bug

#38 [csi] Add patch for fake volume expansion support
  images/csi-nfs/patches/0003-fake-implementation-of-ControllerExpandVolume.patch
  images/csi-nfs/werf.inc.yaml
  templates/csi/controller.yaml
Labels: enhancement

#40 [controller] Fix Helm lib
  charts/deckhouse_lib_helm-1.31.0.tgz
  charts/helm_lib/Chart.yaml
  charts/helm_lib/LICENSE
  charts/helm_lib/README.md
  charts/helm_lib/templates/_api_version_and_kind.tpl
  charts/helm_lib/templates/_csi_controller.tpl
  charts/helm_lib/templates/_csi_node.tpl
  charts/helm_lib/templates/_enable_ds_eviction.tpl
  charts/helm_lib/templates/_envs_for_proxy.tpl
  charts/helm_lib/templates/_high_availability.tpl
  charts/helm_lib/templates/_kube_rbac_proxy.tpl
  charts/helm_lib/templates/_module_documentation_uri.tpl
  charts/helm_lib/templates/_module_ephemeral_storage.tpl
  charts/helm_lib/templates/_module_generate_common_name.tpl
  charts/helm_lib/templates/_module_https.tpl
  charts/helm_lib/templates/_module_image.tpl
  charts/helm_lib/templates/_module_ingress_class.tpl
  charts/helm_lib/templates/_module_init_container.tpl
  charts/helm_lib/templates/_module_labels.tpl
  charts/helm_lib/templates/_module_name.tpl
  charts/helm_lib/templates/_module_public_domain.tpl
  charts/helm_lib/templates/_module_security_context.tpl
  charts/helm_lib/templates/_module_storage_class.tpl
  charts/helm_lib/templates/_monitoring_grafana_dashboards.tpl
  charts/helm_lib/templates/_monitoring_prometheus_rules.tpl
  charts/helm_lib/templates/_node_affinity.tpl
  charts/helm_lib/templates/_pod_disruption_budget.tpl
  charts/helm_lib/templates/_priority_class.tpl
  charts/helm_lib/templates/_resources_management.tpl
  charts/helm_lib/templates/_spec_for_high_availability.tpl
Labels: enhancement
