Repository deckhouse/csi-nfs, pull requests merged in 2024-05, with the labels that each got.

#3 [controller] Add NFSStorageClass CRD
  crds/doc-ru-nfsstorageclass.yaml
  crds/nfsstorageclass.yaml
Labels: enhancement

#5 Add docs
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/README.md
  docs/README_RU.md
Labels: documentation

#6 [csi] Fix hostname resolve
  images/csi-nfs/werf.inc.yaml
Labels: bug

#8 [docs] Add examples
  .github/workflows/deploy_dev.yml
  crds/doc-ru-crd-csi-snapshot.yaml
  crds/doc-ru-nfsstorageclass.yaml
  crds/nfsstorageclass.yaml
  docs/CONFIGURATION.md
  docs/CONFIGURATION.ru.md
  docs/CR.md
  docs/CR.ru.md
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/README.md
  docs/README_RU.md
Labels: documentation

#10 [controller] Remove subDir parameter from NFSStorageClass
  crds/crd-csi-snapshot.yaml
  crds/doc-ru-crd-csi-snapshot.yaml
  crds/doc-ru-nfsstorageclass.yaml
  crds/nfsstorageclass.yaml
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/README.md
  docs/README_RU.md
  images/controller/api/v1alpha1/nfs_storage_class.go
  images/controller/pkg/controller/nfs_storage_class_watcher_func.go
  images/controller/pkg/controller/nfs_storage_class_watcher_test.go
Labels: enhancement

#11 [internal] Add secrets and storageclasses cleanup
  .werf/python-deps.yaml
  hooks/remove_sc_and_secrets_on_module_delete.py
  lib/python/requirements.txt
Labels: bug
