Repository deckhouse/csi-nfs, pull requests merged in 2025-04, with the labels that each got.

#85 [internal] add base64-encoded moduleconfig values validation
  openapi/config-values.yaml
Labels: enhancement

#86 [internal] correct webhooks certificate generation, fix CI and add dmt check
  .github/workflows/build_dev.yml
  .github/workflows/deploy_dev.yml
  hooks/go/020-webhook-certs/webhook-certs.go
  hooks/go/consts/consts.go
Labels: enhancement

#76 [docs] Update license header in go files
  api/LICENSE
  api/v1alpha1/module_config.go
  api/v1alpha1/nfs_storage_class.go
  api/v1alpha1/register.go
  api/v1alpha1/zz_generated.deepcopy.go
  hooks/go/020-webhook-certs/webhook-certs.go
  hooks/go/030-remove-sc-and-secrets-on-module-delete/remove-sc-and-secrets-on-module-delete.go
  hooks/go/LICENSE
  hooks/go/consts/consts.go
  hooks/go/main.go
  images/controller/LICENSE
  images/controller/cmd/main.go
  images/controller/pkg/config/config.go
  images/controller/pkg/controller/controller_suite_test.go
  images/controller/pkg/controller/mc_watcher.go
  images/controller/pkg/controller/nfs_storage_class_watcher.go
  images/controller/pkg/controller/nfs_storage_class_watcher_func.go
  images/controller/pkg/controller/nfs_storage_class_watcher_test.go
  images/controller/pkg/controller/node_selector_reconciler.go
  images/controller/pkg/controller/node_selector_reconciler_test.go
  images/controller/pkg/kubutils/kubernetes.go
  images/controller/pkg/logger/logger.go
  images/csi-nfs-scheduler-extender/LICENSE
  images/csi-nfs-scheduler-extender/cmd/main.go
  images/csi-nfs-scheduler-extender/pkg/consts/consts.go
  images/csi-nfs-scheduler-extender/pkg/kubutils/kubernetes.go
  images/csi-nfs-scheduler-extender/pkg/logger/logger.go
  images/csi-nfs-scheduler-extender/pkg/scheduler/api.go
  images/csi-nfs-scheduler-extender/pkg/scheduler/filter.go
  images/csi-nfs-scheduler-extender/pkg/scheduler/filter_test.go
  images/csi-nfs-scheduler-extender/pkg/scheduler/func.go
  images/csi-nfs-scheduler-extender/pkg/scheduler/func_test.go
  images/csi-nfs-scheduler-extender/pkg/scheduler/prioritize.go
  images/csi-nfs-scheduler-extender/pkg/scheduler/prioritize_test.go
  images/csi-nfs-scheduler-extender/pkg/scheduler/route.go
  images/tlshd/LICENSE
  images/tlshd/cmd/main.go
  images/wait-rpcbind/LICENSE
  images/wait-rpcbind/cmd/main.go
  images/webhooks/LICENSE
  images/webhooks/cmd/main.go
  images/webhooks/handlers/func.go
  images/webhooks/handlers/mcValidator.go
  images/webhooks/handlers/nscValidator.go
  images/webhooks/handlers/scValidator.go
  lib/go/common/LICENSE
  lib/go/common/pkg/feature/const_ce.go
  lib/go/common/pkg/feature/const_csepro.go
  lib/go/common/pkg/feature/const_ee.go
  lib/go/common/pkg/feature/const_se.go
  lib/go/common/pkg/feature/const_seplus.go
  lib/go/common/pkg/feature/feature.go
  lib/go/common/pkg/validating/validator.go
Labels: enhancement

#83 fix logging
  images/controller/pkg/controller/nfs_storage_class_watcher.go
Labels: documentation

#87 [internal] fix masked tlshd
  .github/workflows/go_modules_check.yaml
  crds/doc-ru-nfsstorageclass.yaml
  crds/nfsstorageclass.yaml
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/README.md
  docs/README_RU.md
  images/tlshd/werf.inc.yaml
  templates/csi/controller.yaml
  templates/nodegroupconfiguration-tlshd-masked.yml
Labels: bug

#89 [internal] Switch to build with base-images
  .github/workflows/build_dev.yml
  .github/workflows/build_prod.yml
  .github/workflows/go_checks.yaml
  .werf/base-images.yaml
  .werf/bundle.yaml
  .werf/choice-edition.yaml
  .werf/consts.yaml
  .werf/images-digests.yaml
  .werf/python-deps.yaml
  .werf/release.yaml
  api/go.mod
  api/go.sum
  charts/deckhouse_lib_helm-1.46.2.tgz
  charts/deckhouse_lib_helm-1.50.1.tgz
  hooks/go/go.mod
  hooks/go/go.sum
  images/controller/go.mod
  images/controller/go.sum
  images/controller/werf.inc.yaml
  images/csi-nfs-scheduler-extender/go.mod
  images/csi-nfs-scheduler-extender/go.sum
  images/csi-nfs-scheduler-extender/werf.inc.yaml
  images/csi-nfs/werf.inc.yaml
  images/go-hooks/werf.inc.yaml
  images/kmod/werf.inc.yaml
  images/tlshd/go.mod
  images/tlshd/werf.inc.yaml
  images/wait-rpcbind/go.mod
  images/wait-rpcbind/werf.inc.yaml
  images/webhooks/go.mod
  images/webhooks/go.sum
  images/webhooks/werf.inc.yaml
  lib/go/common/go.mod
  lib/go/common/go.sum
  templates/csi/controller.yaml
  werf-giterminism.yaml
  werf.yaml
Labels: enhancement
